-- AlterTable
ALTER TABLE "GROUPS" ADD COLUMN     "status" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "INGREDIENTS" ADD COLUMN     "status" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "LOCATIONS" ADD COLUMN     "status" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "PRODUCTS" ADD COLUMN     "status" BOOLEAN NOT NULL DEFAULT true;
