-- AlterTable
ALTER TABLE "GROUPS" ALTER COLUMN "codgru" DROP NOT NULL;

-- AlterTable
ALTER TABLE "INGREDIENTS" ALTER COLUMN "coding" DROP NOT NULL;

-- AlterTable
ALTER TABLE "MOVIMENTS" ALTER COLUMN "codmov" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PRODUCTS" ALTER COLUMN "codpro" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PRODUCT_INGREDIENTS" ALTER COLUMN "codpin" DROP NOT NULL;

-- AlterTable
ALTER TABLE "ROLES" ALTER COLUMN "codrol" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SALES" ALTER COLUMN "codsal" DROP NOT NULL;

-- AlterTable
ALTER TABLE "USERS" ALTER COLUMN "codusu" DROP NOT NULL;
